### PR TITLE
remove Laura from Team list (Intern)

### PR DESCRIPTION
**Pull request by AdamJ**
Remove Laura from active team list, as her internship has ended.

### CODE REVIEW

**Comment by ppitonak** [comment]
test this

**Comment by kwk** [comment]
[test]

**Comment by AdamJ** [comment]
@kwk what is the [test] for?

**Comment by kwk** [comment]
> @kwk what is the [test] for?

that's suppose to be a hook to trigger a rebuild

**Review by kwk — APPROVED** [review]
LGTM

**Pull request merged**
