### PR TITLE
Add a UX folder for storage of visuals and documentation

### PR DESCRIPTION
**Pull request by AdamJ**
This PR is for adding a UX directory for storage of visuals and documentation, following the UXD Design Contribution Guidelines. Instead of having documentation in a separate directory, it would live here for consumption.

Existing folder and images removed from _blueprints and placed inside of their correct folder.

### CODE REVIEW

**Comment by sbose78** [comment]
@mindreeper2420 

I checked out your branch and successfully ran the dev docs.
I found the doc served under http://localhost:4000/ux/...

Let me know that's what you intended to do. In any case it looked fine to me, except that there was no way to reach the UX path from index.html ( landing page ).

**Comment by sbose78** [comment]
[test]

**Comment by sbose78** [comment]
Hi @kwk ,
The build is failing because of a network issue I am guessing.

```
01:04:53 Fetching upstream changes from https://github.com/almighty/almighty-devdoc.git
01:04:53  > git -c core.askpass=true fetch --tags --progress https://github.com/almighty/almighty-devdoc.git +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/*
01:04:53 ERROR: Error fetching remote repo 'origin'
01:04:53 hudson.plugins.git.GitException: Failed to fetch from https://github.com/almighty/almighty-devdoc.git
01:04:53    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
01:04:53    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1066)
01:04:53    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
01:04:53    at hudson.scm.SCM.checkout(SCM.java:484)
01:04:53    at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
01:04:53    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:622)
01:04:53    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
01:04:53    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
01:04:53    at hudson.model.Run.execute(Run.java:1759)
01:04:53    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
01:04:53    at hudson.model.ResourceController.execute(ResourceController.java:89)
01:04:53    at hudson.model.Executor.run(Executor.java:240)
```

Do you know a workaround?

**Comment by AdamJ** [comment]
@sbose78 The URL shown was intended (http://localhost:4000/ux/, which should end up being http://devdoc.almighty.io/ux). I'll have to look at adding the link back to the homepage to get to the UX section. Not too familiar with how the URL configs are done with this format though.

I'm not too sure about the network issue. All of the PRs for devdoc are failing, and I'm guessing they are around the same thing.

**Comment by kwk** [comment]
[test]

**Comment by AdamJ** [comment]
@kwk @sbose78 can either of you take a look at this? Everything built locally and all of the links worked without issue. I'll squash with the merge. Thanks!

**Review by sbose78 — APPROVED** [review]
Looks good.

**Comment by sbose78** [comment]
@mindreeper2420 
Please rebase ,  squash and push.

**Pull request merged**
