### PR TITLE
Adding Folder and File for UX Research

### PR DESCRIPTION
**Pull request by Mgranfie**
Adding a first file on the UX research and strategy.

---

This change is [Reviewable](https://reviewable.io/reviews/almighty/almighty-devdoc/37)

### CODE REVIEW

**Comment by kwk** [comment]
@Mgranfie Please rebase to current master

**Comment by maxandersen** [comment]
Hi @Mgranfie I only see two images added here - did you mean to add some text to explain these too ?

**Comment by maxandersen** [comment]
about rebase I can do that, just wnated to be sure we aren't actually missing something here ?

**Comment by aslakknutsen** [comment]
I renamed the image last time, https://github.com/almighty/almighty-devdoc/tree/master/_blueprints/ux

Text could be added here: https://github.com/almighty/almighty-devdoc/blob/master/_blueprints/ux.adoc

**Comment by Mgranfie** [comment]
I was just trying out how to get images up there.....

**Comment by maxandersen** [comment]
okey, so we can close this as invalid or ?

**Comment by maxandersen** [comment]
ah just saw @aslakknutsen comment. closing this request then.

**Comment by aslakknutsen** [comment]
@Mgranfie For future reference, it would be nice if you could somehow 'tag' a commit/pull request/message with some kind of indicator that this should not be looked at. e.g. Prefix Title with TEST: 

Then we avoid 3-4 people reviewing and trying to understand what you're up to :)

**Comment by Mgranfie** [comment]
Ah Ok sorry, thanks for the info! Will do that.

**Pull request closed without merging**
