### PR TITLE
ALM doc for issue trackers created

### PR DESCRIPTION
**Pull request by Ritsyy**
Issue https://github.com/almighty/almighty-devdoc/issues/10

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Sorry, Could you please make it asciidoc :)

**Comment by aslakknutsen** [comment]
http://asciidoctor.org/docs/asciidoc-writers-guide/

**Comment by Ritsyy** [comment]
yeah, sure

**Comment by kwk** [comment]
@Ritsyy I can recommend [`pandoc`](http://pandoc.org/demos.html) to do the conversion to asciidoc automatically. Here's how you can do it:

```
$ sudo dnf install -y pandoc
$ pandoc -s -t asciidoc --toc almdoc.md -o almdoc.adoc
```

Then you can check in the `almdoc.adoc` and remove the `almdoc.md`.

**Comment by Ritsyy** [comment]
@kwk yes doing this way, thank you so much :)

**Comment by aslakknutsen** [comment]
Are we getting the other Remote Issue Tracker docs in here as well?

**Comment by DhritiShikhar** [comment]
@aslakknutsen This PR contains Trello and Github docs. I will send my PR for Bugzilla and Jira. We can rebase it.

**Comment by aslakknutsen** [comment]
@DhritiShikhar Are you sending a PR with all included? or you waiting for this to go upstream so you can add them and then send a PR? (just trying to clearify, your added 'we can rebase it' comment is throwing my thinking off :)

**Comment by DhritiShikhar** [comment]
@aslakknutsen I will wait for this to go upstream

**Pull request closed without merging**
