### PR TITLE
Add InVision commenting guide

### PR DESCRIPTION
**Pull request by AdamJ**

### CODE REVIEW

**Comment by AdamJ** [comment]
@essjaysee @mgranfie can either of you take a look at this to make sure I didn't make any errors? Thanks!

**Comment by Essjaysee** [comment]
Just read it through, and it all looks in order.  Is there anything I should do to push it along?

**Comment by AdamJ** [comment]
@Essjaysee there should be an option to approve the commit next to 'Review Required' :-) I can merge it at that point.

**Review by Essjaysee — APPROVED** [review]
LGTM, ship it!

**Comment by AdamJ** [comment]
[test]

**Pull request merged**
